name: Print Secret

on: [push]

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Print Secret
      run: echo ${{ secrets.PRACTICE_TEST_SECRET }}
